# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pair < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/philippeckel/pair"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philippeckel/pair/releases/download/0.0.1/pair_Darwin_x86_64.tar.gz"
      sha256 "9a7172dbbb40100a9d3a61795413c524ed0bf9697419a14c151e2199dc2835b5"

      def install
        bin.install "pair"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philippeckel/pair/releases/download/0.0.1/pair_Darwin_arm64.tar.gz"
      sha256 "356bdba1dd3548d627d0ad7862451c29b6089370d365345498aa79c458422068"

      def install
        bin.install "pair"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philippeckel/pair/releases/download/0.0.1/pair_Linux_x86_64.tar.gz"
        sha256 "64d240508c4e1c43808971c030393df42d333cebebb877854885cf0a001961e0"

        def install
          bin.install "pair"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philippeckel/pair/releases/download/0.0.1/pair_Linux_arm64.tar.gz"
        sha256 "b2a28be4841d1b04a4f8e4e6c8e76353ce14cbd0c1aaa1050d7ea458a192d41b"

        def install
          bin.install "pair"
        end
      end
    end
  end
end
