# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pair < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/philippeckel/pair"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philippeckel/pair/releases/download/0.0.1/pair_Darwin_x86_64.tar.gz"
      sha256 "da112da511e0a83cd0bf6933245e6045ea4cbc374a6c4d29878b6c80832916e7"

      def install
        bin.install "pair"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philippeckel/pair/releases/download/0.0.1/pair_Darwin_arm64.tar.gz"
      sha256 "81ab9352d30720affbf0805db22df9acedc654ca5a83f8a66a2bc94b90901ce0"

      def install
        bin.install "pair"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philippeckel/pair/releases/download/0.0.1/pair_Linux_x86_64.tar.gz"
        sha256 "5b70495acb6c7e31b25eaed95f4710d7cbb6789328de2b4011bac040cbe6952c"

        def install
          bin.install "pair"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philippeckel/pair/releases/download/0.0.1/pair_Linux_arm64.tar.gz"
        sha256 "a0adfdaefeb81c613a061468dd18be49983e1257489d1d85a50bfb279bb30a4a"

        def install
          bin.install "pair"
        end
      end
    end
  end
end
